In [1]:
import pandas as pd
import json

In [2]:
# Data import
data = pd.read_csv('metadata/moex_emitters.csv', sep=';', encoding='windows-1251')
data.head()

,DATESTAMP,INSTRUMENT_ID,LIST_SECTION,NPP,SUPERTYPE,INSTRUMENT_TYPE,INSTRUMENT_CATEGORY,TRADE_CODE,ISIN,REGISTRY_NUMBER,...,OTHER_SECURITIES,DISCLOSURE_PART_PAGE,DISCLOSURE_RF_INFO_PAGE,INCLUDE_DATE,CFI_FOREIGN,ISIN_UNDERLYING_ASSET,CFI_UNDERLYING_ASSET,PIF_STATUS,PIF_STATUS_HIST,OBLIGATION_PROGRAM_DATE
0,03.03.26 00:00,15348,Первый уровень,1,Облигации,Облигация биржевая,биржевые облигации процентные неконвертируемые...,NaN,NaN,4B02-02-00354-B-003P,...,"Облигация корпоративная, 41900354B, RU000A0ZZF...",https://www.gazprombank.ru,https://www.e-disclosure.ru/portal/company.asp...,04.06.21 00:00,NaN,NaN,NaN,NaN,NaN,27.08.18 00:00
1,03.03.26 00:00,15349,Первый уровень,2,Облигации,Облигация биржевая,биржевые облигации процентные неконвертируемые...,NaN,NaN,4B02-03-00354-B-003P,...,"Облигация корпоративная, 41900354B, RU000A0ZZF...",https://www.gazprombank.ru,https://www.e-disclosure.ru/portal/company.asp...,04.06.21 00:00,NaN,NaN,NaN,NaN,NaN,27.08.18 00:00
2,03.03.26 00:00,15350,Первый уровень,3,Облигации,Облигация биржевая,биржевые облигации процентные неконвертируемые...,NaN,NaN,4B02-04-00354-B-003P,...,"Облигация корпоративная, 41900354B, RU000A0ZZF...",https://www.gazprombank.ru,https://www.e-disclosure.ru/portal/company.asp...,04.06.21 00:00,NaN,NaN,NaN,NaN,NaN,27.08.18 00:00
3,03.03.26 00:00,15351,Первый уровень,4,Облигации,Облигация биржевая,биржевые облигации процентные неконвертируемые...,NaN,NaN,4B02-05-00354-B-003P,...,"Облигация корпоративная, 41900354B, RU000A0ZZF...",https://www.gazprombank.ru,https://www.e-disclosure.ru/portal/company.asp...,04.06.21 00:00,NaN,NaN,NaN,NaN,NaN,27.08.18 00:00
4,03.03.26 00:00,14052,Первый уровень,5,Облигации,Облигация биржевая,биржевые облигации процентные неконвертируемые...,RU000A101Z74,RU000A101Z74,4B02-16-00354-B-001P,...,"Облигация корпоративная, 41900354B, RU000A0ZZF...",https://www.gazprombank.ru,https://www.e-disclosure.ru/portal/company.asp...,24.07.20 00:00,NaN,NaN,NaN,NaN,NaN,16.04.18 00:00

In [3]:
# Columns review
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4142 entries, 0 to 4141
Data columns (total 46 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DATESTAMP                    4142 non-null   object
 1   INSTRUMENT_ID                4142 non-null   int64
 2   LIST_SECTION                 4142 non-null   object
 3   NPP                          4142 non-null   int64
 4   SUPERTYPE                    4142 non-null   object
 5   INSTRUMENT_TYPE              4142 non-null   object
 6   INSTRUMENT_CATEGORY          4142 non-null   object
 7   TRADE_CODE                   3727 non-null   object
 8   ISIN                         3728 non-null   object
 9   REGISTRY_NUMBER              4106 non-null   object
 10  REGISTRY_DATE                4106 non-null   object
 11  EMITENT_FULL_NAME            4142 non-null   object
 12  INN                          4122 non-null   float64
 13  NOMINAL                      3918 non-null   object
 14  CURRENCY                     3918 non-null   object
 15  ISSUE_AMOUNT                 3918 non-null   object
 16  DECISION_DATE                4142 non-null   object
 17  OKSM_EDR                     1 non-null      object
 18  ONLY_EMITENT_FULL_NAME       1 non-null      object
 19  REG_COUNTRY                  17 non-null     object
 20  QUALIFIED_INVESTOR           912 non-null    object
 21  HAS_PROSPECTUS               2385 non-null   object
 22  IS_CONCESSION_AGREEMENT      24 non-null     object
 23  IS_MORTGAGE_AGENT            90 non-null     object
 24  INCLUDED_DURING_CREATION     0 non-null      float64
 25  SECURITY_HAS_DEFAULT         53 non-null     object
 26  SECURITY_HAS_TECH_DEFAULT    89 non-null     object
 27  INCLUDED_WITHOUT_COMPLIANCE  1 non-null      object
 28  RETAINED_WITHOUT_COMPLIANCE  297 non-null    object
 29  HAS_RESTRICTION_CIRCULATION  4 non-null      object
 30  LISTING_LEVEL_HIST           4142 non-null   object
 31  OBLIGATION_PROGRAM_RN        2725 non-null   object
 32  COUPON_PERCENT               3020 non-null   object
 33  EARLY_REPAYMENT              678 non-null    object
 34  EARLY_REDEMPTION             3632 non-null   object
 35  ISS_BOARDS                   3498 non-null   object
 36  OTHER_SECURITIES             3836 non-null   object
 37  DISCLOSURE_PART_PAGE         3812 non-null   object
 38  DISCLOSURE_RF_INFO_PAGE      3968 non-null   object
 39  INCLUDE_DATE                 4142 non-null   object
 40  CFI_FOREIGN                  36 non-null     object
 41  ISIN_UNDERLYING_ASSET        1 non-null      object
 42  CFI_UNDERLYING_ASSET         1 non-null      object
 43  PIF_STATUS                   222 non-null    object
 44  PIF_STATUS_HIST              222 non-null    object
 45  OBLIGATION_PROGRAM_DATE      2725 non-null   object
dtypes: float64(2), int64(2), object(42)
memory usage: 1.5+ MB

In [4]:
data.columns

Index(['DATESTAMP', 'INSTRUMENT_ID', 'LIST_SECTION', 'NPP', 'SUPERTYPE',
       'INSTRUMENT_TYPE', 'INSTRUMENT_CATEGORY', 'TRADE_CODE', 'ISIN',
       'REGISTRY_NUMBER', 'REGISTRY_DATE', 'EMITENT_FULL_NAME', 'INN',
       'NOMINAL', 'CURRENCY', 'ISSUE_AMOUNT', 'DECISION_DATE', 'OKSM_EDR',
       'ONLY_EMITENT_FULL_NAME', 'REG_COUNTRY', 'QUALIFIED_INVESTOR',
       'HAS_PROSPECTUS', 'IS_CONCESSION_AGREEMENT', 'IS_MORTGAGE_AGENT',
       'INCLUDED_DURING_CREATION', 'SECURITY_HAS_DEFAULT',
       'SECURITY_HAS_TECH_DEFAULT', 'INCLUDED_WITHOUT_COMPLIANCE',
       'RETAINED_WITHOUT_COMPLIANCE', 'HAS_RESTRICTION_CIRCULATION',
       'LISTING_LEVEL_HIST', 'OBLIGATION_PROGRAM_RN', 'COUPON_PERCENT',
       'EARLY_REPAYMENT', 'EARLY_REDEMPTION', 'ISS_BOARDS', 'OTHER_SECURITIES',
       'DISCLOSURE_PART_PAGE', 'DISCLOSURE_RF_INFO_PAGE', 'INCLUDE_DATE',
       'CFI_FOREIGN', 'ISIN_UNDERLYING_ASSET', 'CFI_UNDERLYING_ASSET',
       'PIF_STATUS', 'PIF_STATUS_HIST', 'OBLIGATION_PROGRAM_DATE'],
      dtype='object')

In [5]:
# Looking for stocks
data['SUPERTYPE'].value_counts()

SUPERTYPE
Облигации                        3632
Акции                             260
Инвестиционные паи                222
Еврооблигации                      26
Депозитарные расписки               1
Ипотечные сертификаты участия       1
Name: count, dtype: int64

In [6]:
# Stock selection
data[data['SUPERTYPE'] == 'Акции'][['TRADE_CODE', 'ISIN', 'EMITENT_FULL_NAME', 'ISSUE_AMOUNT']]

,TRADE_CODE,ISIN,EMITENT_FULL_NAME,ISSUE_AMOUNT
11,CBOM,RU000A0JUG31,"""МОСКОВСКИЙ КРЕДИТНЫЙ БАНК"" (публичное акционе...",33429709866
17,ALRS,RU0007252813,"Акционерная компания ""АЛРОСА"" (публичное акцио...",7364965630
72,VTBR,RU000A0JP5V6,Банк ВТБ (публичное акционерное общество),6620418282
95,MDMG,RU000A108KL3,Международная Компания Публичное Акционерное О...,75125010
96,GEMC,RU000A107JE2,Международная Компания Публичное Акционерное О...,90000000
...,...,...,...,...
3972,SAGOP,RU0009084495,Публичное акционерное общество энергетики и эл...,364918444
3973,SLEN,RU0009280465,Публичное акционерное общество энергетики и эл...,2237123773
4016,PRMB,RU000A0DPNQ5,"акционерный коммерческий банк ""Приморье"" (пуб...",250000
4115,KMEZ,RU0006753613,"публичное акционерное общество ""Ковровский мех...",3764600
4140,ARSA,RU000A0JP0Q7,"публичное акционерное общество ""Управляющая ко...",123817165

In [7]:
# Drop NaNs
df_stocks = data[data['SUPERTYPE'] == 'Акции'][['TRADE_CODE', 'ISIN', 'EMITENT_FULL_NAME', 'ISSUE_AMOUNT']].copy()
df_stocks = df_stocks.dropna(subset=['TRADE_CODE'])
df_stocks

,TRADE_CODE,ISIN,EMITENT_FULL_NAME,ISSUE_AMOUNT
11,CBOM,RU000A0JUG31,"""МОСКОВСКИЙ КРЕДИТНЫЙ БАНК"" (публичное акционе...",33429709866
17,ALRS,RU0007252813,"Акционерная компания ""АЛРОСА"" (публичное акцио...",7364965630
72,VTBR,RU000A0JP5V6,Банк ВТБ (публичное акционерное общество),6620418282
95,MDMG,RU000A108KL3,Международная Компания Публичное Акционерное О...,75125010
96,GEMC,RU000A107JE2,Международная Компания Публичное Акционерное О...,90000000
...,...,...,...,...
3972,SAGOP,RU0009084495,Публичное акционерное общество энергетики и эл...,364918444
3973,SLEN,RU0009280465,Публичное акционерное общество энергетики и эл...,2237123773
4016,PRMB,RU000A0DPNQ5,"акционерный коммерческий банк ""Приморье"" (пуб...",250000
4115,KMEZ,RU0006753613,"публичное акционерное общество ""Ковровский мех...",3764600
4140,ARSA,RU000A0JP0Q7,"публичное акционерное общество ""Управляющая ко...",123817165

In [8]:
df_stocks[df_stocks['ISSUE_AMOUNT'] == '3854341416571,43']

,TRADE_CODE,ISIN,EMITENT_FULL_NAME,ISSUE_AMOUNT
641,TGKA,RU000A0JNUD0,"Публичное акционерное общество ""Территориальна...","3854341416571,43"

In [9]:
# Stock extraction
metadata = {}
for _, row in df_stocks.iterrows():
    ticker = row['TRADE_CODE']
    issue_amount = row['ISSUE_AMOUNT']
    
    if pd.notna(issue_amount):
        # Format correction 
        issue_amount = int(float(str(issue_amount).replace(',', '.')))
    else:
        issue_amount = None

    metadata[ticker] = {
        "isin": row['ISIN'],
        "name": row['EMITENT_FULL_NAME'],
        "sector": "Unknown",
        "issue_amount": issue_amount
    }

# Save to JSON
with open('metadata/companies.json', 'w', encoding='utf-8') as f:
    json.dump(metadata, f, ensure_ascii=False, indent=2)

print(f"Сохранено {len(metadata)} записей")

Сохранено 260 записей